---
title: "Bombus haemolymph diapause study"
output: bombus_queen_haemolymph_structural_lfq_line_plots.html
authors: Joe Colgan (joscolgan)
---

## Introduction:
=============

The purpose of this script is to take label-free quantification (LFQ) values generated by the software program, [Perseus](https://www.biochem.mpg.de/5111810/perseus) and generate line plots using [ggplot2](https://ggplot2.tidyverse.org/).  
The output of this script is an image (saved in either png, jpeg and pdf format).

```{r, message = FALSE}
## Load libraries:
libraries <- c("lintr",
               "ggplot2",
               "ggpubr",
               "reshape",
               "Rmisc",
               "matrixStats")
for (lib in libraries) {
        if (require(package = lib, character.only = TRUE)) {
                print("Successful")
        } else {
                print("Installing")
                source("https://bioconductor.org/biocLite.R")
                biocLite(pkgs = lib)
                library(lib, character.only = TRUE )
        }
}
```

Load in data:

```{r, echo=FALSE}
## Read in data and store as a variable:
lfq_values <- read.table(file = "input/input_for_plots.txt",
                         header = TRUE)

## Subset:
rownames(lfq_values) <- lfq_values$T._Protein_ID
lfq_values_subset <- lfq_values[, 3:26]

## Need to be able to subset genes of interest:
proteins_of_interest <- read.table(file = "data/muscle_proteins_reduced.txt",
                              header = FALSE)

## Update column names:
colnames(proteins_of_interest) <- c("description", "protein_id")

## Subset proteins of interest:
tmp <- subset(lfq_values_subset, row.names(lfq_values_subset)
              %in% proteins_of_interest$protein_id)

## Add protein description:
tmp$description <- proteins_of_interest$description

## Update description name:
rownames(tmp) <- gsub("_", " ", tmp$description)
tmp$description <- NULL

## Remove species ID:
row.names(tmp) <- gsub("Bombus terrestris",
                       "",
                       row.names(tmp))
row.names(tmp) <- gsub("\\[]",
                       "",
                       row.names(tmp))
row.names(tmp) <- gsub("_",
                       " ",
                       row.names(tmp))

## Subset protein names:
colnames(tmp) <- c(rep("gyne", 4),
                   rep("pre-diapause", 4),
                   rep("early diapause", 4),
                   rep("late diapause", 4),
                   rep("6 hrs postdiapause", 4),
                   rep("48 hrs postdiapause", 4))

## Reshape:
tmp_melt <- melt(t(tmp))

## Update column names:
colnames(tmp_melt) <- c("Stage",
                        "Protein",
                        "LFQ")

## Plot line plot:
tmp_melt$Stage <- factor(tmp_melt$Stage,
                         levels = c("gyne",
                                    "pre-diapause",
                                    "early diapause",
                                    "late diapause",
                                    "6 hrs postdiapause",
                                    "48 hrs postdiapause"))

## Summarise LFQ values to get standard deviation, standard error of the mean and a default (95%) confidence interval:      
tmp_melt_SE <- summarySE(tmp_melt,
                         measurevar = "LFQ",
                         groupvars = c("Stage",
                                       "Protein"))

## Print
tmp_melt_SE
```

Generate line graphs:

```{r}
## Add a value to slightly adjust the plotting of values:
pd <- position_dodge(0.05) # move them .05 to the left and right

## Define title:
plot_title <- "Cuticular and muscular proteins"

## Generate plot:
line_plot <- ggplot(tmp_melt_SE,
                    aes(x = Stage,
                        y = LFQ,
                        colour = Protein,
                        group = Protein)) +
                    geom_errorbar(aes(ymin = LFQ - se,
                                      ymax = LFQ + se),
                                  colour = "black",
                                  width = .1,
                                  position = pd) +
                    geom_line(position = pd,
                              size = 1.5) +
                    geom_point(position = pd,
                               size = 3,
                               shape = 21) + # 21 is filled circle
                    ylab("LFQ values") +
                    theme_bw() +
                    theme(legend.position = "bottom",
                          legend.text = element_text(size = 12),
                          legend.title = element_text(size = 12,
                                                      face = "bold"),
                          axis.title.x = element_blank(),
                          axis.text.x = element_text(angle = 45,
                                                     hjust = 1,
                                                     size = 12,
                                                     face = "bold"),
                          axis.title.y = element_text(face = "bold",
                                                      size = 15),
                          axis.text.y = element_text(size = 10))

## Update legend title:
line_plot <- line_plot +
        guides(fill = guide_legend(title = "Protein IDs"))

## Change the colour pallete of the plot:
line_plot <- line_plot +
             scale_color_brewer(palette = "Spectral")

## Add label:
annotated_line_plot <- ggarrange(line_plot,
                                 labels = c("B"))

## Create output directory:
dir.create(path = "./results/pdf/",
           recursive = TRUE)

## Define output:
output_pdf <- "results/muscle_lfq_line_plot.pdf"

## Save output:
ggsave(output_pdf,
       dpi = 600,
       height = 8,
       width = 13)

## Create output directory:
dir.create(path = "./results/png/",
           recursive = TRUE)

## Define output:
output_png <- "results/muscle_lfq_line_plot.png"

## Save output:
ggsave(output_png,
       height = 8,
       width = 13)

## Create output directory:
dir.create(path = "./results/rdata/",
           recursive = TRUE)

## Save output:
save(line_plot,
     file = "results/rdata/structural_lfq_line_plot.Rdata")
```

Run lintr:

```{r, message = FALSE}
## Run lintr:
lintr::lint(file = "./bombus_queen_haemolymph_structural_lfq_line_plots.Rmd")
```
