--- 
title: "Bombus haemolymph diapause study"
output: bombus_queen_haemolymph_pca.html
authors: Joe Colgan (joscolgan)
--- 

## Introduction:
The purpose of this script is to take label-free quantification (LFQ) values from the software program, Perseus, normalise and perform a principal component analysis. Two principal components are then plotted using the R package, ggplot2. 

```{r, message = FALSE}
# Load libraries; install from scratch if needed
libraries <- c("ggplot2",
               "ggfortify",
               "RColorBrewer",
               "ggpubr")
for (lib in libraries) {
    if (require(package = lib, character.only = TRUE)) {
        print("Successful")
    } else {
        print("Installing")
        source("https://bioconductor.org/biocLite.R")
        biocLite(pkgs = lib)
        library(lib, character.only = TRUE )
    }
}
dir.create("results")
```

Read in input data:

```{r}
## Read in data and store as a dataframe:
haem_data <- read.table(file = "input/diapause_results_111118_for_pca.txt",
                        header = TRUE)

## Assign the first column containing protein_id to the rowname:
rownames(haem_data) <- haem_data$T._Protein_ID

## Remove the protein ID column:
haem_data$T._Protein_ID <- NULL
haem_data$T._Fasta_headers <- NULL

## Transpose:
haem_data_df <- as.data.frame(t(haem_data))

## Add a column indicating life cycle 'stage':
rownames(haem_data_df)

## Update stage:
life_stages <- c(rep("gyne", 4),
                 rep("pre-diapause", 4),
                 rep("early diapause", 4),
                 rep("late diapause", 4),
                 rep("6 hrs postdiapause", 4),
                 rep("48 hours postdiapause", 4))

## Add column for life cycle stage:
haem_data_df$life_stages <- life_stages

## Add levels for plotting:
haem_data_df$life_stages <- factor(haem_data_df$life_stages,
                             levels = c(unique(as.character(unlist(haem_data_df$life_stages)))))

## Subset for plotting:
haem_data_subset <- haem_data_df[, c(1:79)]
```

Perform PCA and plot:

```{r}
## Perform PCA:
haem_data_subset_pca <- prcomp(haem_data_subset,
                               center = TRUE,
                               scale. = TRUE)

## Plot all principal components:
plot(haem_data_subset_pca,
     type = "l")
```

Plot a number of principal components:

```{r, message = FALSE}
## Plot
pca_plot_1_2 <- autoplot(prcomp(haem_data_subset),
                         x = 1,
                         y = 2,
                         data = haem_data_df,
                         colour = "life_stages",
                         fill = "black",
                         size = 4) +
        scale_color_brewer(type = "qual",
                           palette = "RdBu") +
        geom_point(aes(colour = haem_data_df$life_stages),
                   size = 6) +
        geom_point(shape = 1,
                   size = 6,
                   colour = "black") +
        theme_bw() +
        theme(axis.text = element_text(size = 15),
              legend.title = element_text(size = 10,
                                         face = "bold"),
              axis.title = element_text(size = 15,
                                        face = "bold")) +
        labs(color = "Life stages")

## Plot principal components 1 and 3:
pca_plot_1_3 <- autoplot(prcomp(haem_data_subset),
                         x = 1,
                         y = 3,
                         data = haem_data_df,
                         colour = "life_stages",
                         fill = "black",
                         size = 4) +
        scale_color_brewer(type = "qual",
                           palette = "RdBu") +
        geom_point(aes(colour = haem_data_df$life_stages),
                   size = 6) +
        geom_point(shape = 1,
                   size = 6,
                   colour = "black") +
        theme_bw() +
        theme(axis.text = element_text(size = 15),
              legend.title = element_text(size = 10,
                                         face = "bold"),
              axis.title = element_text(size = 15,
                                        face = "bold")) +
        labs(color = "Life stages")

## Plot principal components 1 and 4:
pca_plot_1_4 <- autoplot(prcomp(haem_data_subset),
                         x = 1,
                         y = 4,
                         data = haem_data_df,
                         colour = "life_stages",
                         fill = "black",
                         size = 4) +
        scale_color_brewer(type = "qual",
                           palette = "RdBu") +
        geom_point(aes(colour = haem_data_df$life_stages),
                   size = 6) +
        geom_point(shape = 1,
                   size = 6,
                   colour = "black") +
        theme_bw() +
        theme(axis.text = element_text(size = 15),
              legend.title = element_text(size = 10,
                                         face = "bold"),
              axis.title = element_text(size = 15,
                                        face = "bold")) +
        labs(color = "Life stages")

## Plot principal components 1 and 5:
pca_plot_1_5 <- autoplot(prcomp(haem_data_subset),
                         x = 1,
                         y = 5,
                         data = haem_data_df,
                         colour = "life_stages",
                         fill = "black",
                         size = 4) +
        scale_color_brewer(type = "qual",
                           palette = "RdBu") +
        geom_point(aes(colour = haem_data_df$life_stages),
                   size = 6) +
        geom_point(shape = 1,
                   size = 6,
                   colour = "black") +
        theme_bw() +
        theme(axis.text = element_text(size = 15),
              legend.title = element_text(size = 10,
                                         face = "bold"),
              axis.title = element_text(size = 15,
                                        face = "bold")) +
        labs(color = "Life stages")
```

Plot together:

```{r}
## Plot together:
ggarrange(pca_plot_1_2,
          pca_plot_1_3,
          pca_plot_1_4,
          pca_plot_1_5,
          labels = c("A",
                     "B",
                     "C",
                     "D"),
          nrow = 2,
          ncol = 2,
          common.legend = TRUE)

## Save as a .png file:
ggsave(file = "results/figure_2_pca_plot.pdf",
       dpi = 600,
       height = 10,
       width = 10)
```

Check style:

```{r, message = FALSE}
## Run lintr:
lintr::lint(file = "./bombus_queen_haemolymph_pca.Rmd")
```


