--- 
title: "Bombus haemolymph diapause study"
output: gene_level_differential_expression_diapause.html
authors: Joe Colgan (joscolgan)
--- 

Introduction:
=============

The purpose of this script is to take label-free quantification (LFQ) values from the software program, Perseus, log transform and plot as boxplots using the R package, ggplot2. 

1. Load libraries:

```{r}
# Load libraries; install from scratch if needed
libraries <- c("ggplot2", "ggfortify", "RColorBrewer", "ggpubr", "reshape")
for (lib in libraries) {
    if (require(package = lib, character.only = TRUE)) {
        print("Successful")
    } else {
        print("Installing")
        source("https://bioconductor.org/biocLite.R")
        biocLite(pkgs = lib)
        library(lib, character.only = TRUE )
    }
}

## Script will comlain if already exists:
dir.create("results")
```

1. Read in input data:

```{r, message = FALSE}
## Read in data and store as a dataframe:
haem_data <- read.table(file = "input/input_for_plots.txt",
                        header = TRUE)

## Assign the first column containing protein_id to the rowname:
rownames(haem_data) <- haem_data$T._Protein_ID

## Subset columns containing intensity values:
haem_data_subset <- haem_data[,3:26]
head(haem_data_subset)

## Transpose:
haem_data_df <- as.data.frame(t(haem_data_subset))

## Add a column indicating life-cycle 'stage':
rownames(haem_data_df)

## Create a vector of life-cycle stages:
stage <- c(rep("gyne", 4),
           rep("prediapause", 4),
           rep("early diapause", 4),
           rep("late diapause", 4),
           rep("6 hrs postdiapause", 4),
           rep("48 hours postdiapause", 4))

## Add stage: 
haem_data_df$stage <- stage 

## Add levels for plotting:
haem_data_df$stage <- factor(haem_data_df$stage, levels = c(unique(as.character(unlist(haem_data_df$stage)))))
```

2. Subset proteins of interest and plot:

```{r, message = FALSE}
## Subset based on a list of proteins:
proteins_of_interest <- read.table(file = "data/olfaction_proteins.txt",
                              header = FALSE)

## Update column names:
colnames(proteins_of_interest) <- c("description", "protein_id")

## Calculate z_scores:
class(lfq_values_subset)
test_sd <- transform(as.matrix(lfq_values_subset),
          SD = rowSds(as.matrix(lfq_values_subset),
                    na.rm = TRUE))

test_mean <- transform(as.matrix(test_sd),
                       mean = rowMeans(as.matrix(test_sd[, 1:24]),
                                 na.rm = TRUE))

## For eac column, substract the row mean and divide by the standard deviation:
for (row in 1:nrow(test_mean)){
        print(row)
        test_mean[row, ] <- (test_mean[row, ] - test_mean$mean[row]) / test_mean$SD[row]
}

## Remove mean and SD:
test_mean$SD <- NULL
test_mean$mean <- NULL

## Subset proteins of interest:
tmp <- subset(test_mean, row.names(test_mean)
              %in% proteins_of_interest$protein_id)

tmp$description <- row.names(tmp)

## Subset protein names:
colnames(tmp) <- c(rep("Virgin queen (Gyne)", 4),
                   rep("Prediapause", 4),
                   rep("Early diapause", 4),
                   rep("Late diapause", 4),
                   rep("6 hrs postdiapause", 4),
                   rep("48 hours postdiapause", 4),
                   "description")

## Make sure it is a dataframe:
tmp_df <- as.data.frame(tmp)

## Reshape for plotting:
tmp_df_melt <- t(tmp_df)

## Update column names:
colnames(tmp_df_melt) <- c("Protein", "Life_Stage", "Normalised_LFQ")

bp <- ggplot(tmp_df_melt,
             aes(x = Life_Stage,
                 y = Normalised_LFQ,
                 group = Life_Stage)) + 
        geom_boxplot(aes(fill = Life_Stage))

bp + facet_grid(. ~ Protein)


bp <- ggplot(tmp_df_melt,
                       aes(x = Life_Stage,
                           y = Normalised_LFQ,
                           aes(fill = Life_Stage))) +
                #geom_boxplot(aes(fill = Life_Stage)) +
                     geom_boxplot() +
                xlab("Life stage") +
                ylab("Normalised values") +
                #ylim(c(24,35)) +
                theme(legend.position="none") +
                ggtitle("Olfaction-related proteins") +
                scale_fill_brewer(type = "qual",
                                  palette = "RdBu") +
                theme_bw() +
                theme(legend.position = "top")

bp <- bp +
                theme(axis.text=element_text(size=15),
                axis.title= element_text(size=15,face="bold"), 
                axis.text.x = element_blank())

bp + facet_grid(. ~ Protein, scales = "free", space = "free")

## Define output:
output <- "results/olfaction_box_plots.png"

## Save output:
ggsave(output,
       height = 10,
       width = 20)
```
