---
title: "Bombus haemolymph diapause study"
output: combined_olfaction_structural_plot.html
authors: Joe Colgan (joscolgan)
---

## Introduction:
The purpose of this script is take two previously plots generated by ggplot2 and generate a multi-image plot. 

```{r, message = FALSE}
## Load libraries:
libraries <- c("lintr",
               "ggplot2",
               "ggpubr")
for (lib in libraries) {
        if (require(package = lib, character.only = TRUE)) {
                print("Successful")
        } else {
                print("Installing")
                source("https://bioconductor.org/biocLite.R")
                biocLite(pkgs = lib)
                library(lib, character.only = TRUE )
        }
}
```

Load R objects containing:
1) A boxplot for olfaction-related genes.
2) A line plot for structural and muscular-related genes.

```{r, message = FALSE}
load(file = "./results/rdata/olfaction_lfq_box_plot.Rdata")
load(file = "./results/rdata/structural_lfq_line_plot.Rdata")
```

Generate combined plot:

```{r, message = FALSE}
## Generate plot:
ggarrange(combined_boxplot,
          line_plot,
          ncol = 1,
          nrow = 2,
          heights = c(2.0,
                      1.5),
          align = "hv",
          labels = c("A",
                     "B"))

## Create output directory:
dir.create(path = "./results/pdf/",
           recursive = TRUE)

## Define output:
output_pdf <- "./results/pdf/figure_4.pdf"

## Save image:
ggsave(file = output_pdf,
       dpi = 600,
       height = 16,
       width = 14)

## Create output directory:
dir.create(path = "./results/png/",
           recursive = TRUE)

## Define output:
output_png <- "./results/png/figure_4.png"

## Save image:
ggsave(file = output_png,
       height = 16,
       width = 14)
```

Run lintr:

```{r, message = FALSE}
lintr::lint(file = "./combined_olfaction_structural_plot.Rmd")
```
